"""empty message

Revision ID: 45edcd2f0fcb
Revises: 
Create Date: 2022-01-21 11:16:49.150377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45edcd2f0fcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shelfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('shelf_id', sa.Integer(), nullable=True),
    sa.Column('is_on_shelf', sa.Boolean(), nullable=True),
    sa.Column('publishing_house', sa.String(length=128), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelfs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('shelfs')
    op.drop_table('users')
    op.drop_table('cities')
    # ### end Alembic commands ###
