"""empty message

Revision ID: c058d6d6718a
Revises: 45edcd2f0fcb
Create Date: 2022-01-21 11:29:18.842305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c058d6d6718a'
down_revision = '45edcd2f0fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publication_year', sa.Integer(), nullable=True))
    op.drop_column('books', 'publication_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publication_date', sa.DATE(), nullable=True))
    op.drop_column('books', 'publication_year')
    # ### end Alembic commands ###
